package com.sqvizers.forgeborncore.mixin.worldgen;

import net.minecraft.core.Holder;
import net.minecraft.world.level.biome.BiomeGenerationSettings;
import net.minecraft.world.level.levelgen.GenerationStep;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;

import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

import java.util.List;

/** Removes biome placed-feature ores; GT veins are generated by GT's separate OreGenerator. */
@Mixin(BiomeGenerationSettings.PlainBuilder.class)
public abstract class BiomeOreFeatureStripMixin {

    @Shadow
    @Final
    protected List<List<Holder<PlacedFeature>>> features;

    @Inject(method = "build", at = @At("HEAD"))
    private void forgeborncore$removeNonGtOreFeatures(CallbackInfoReturnable<BiomeGenerationSettings> cir) {
        int oreStep = GenerationStep.Decoration.UNDERGROUND_ORES.ordinal();
        if (oreStep < features.size()) {
            features.get(oreStep).removeIf(BiomeOreFeatureStripMixin::forgeborncore$isOreFeature);
        }
    }

    private static boolean forgeborncore$isOreFeature(Holder<PlacedFeature> holder) {
        // Vanilla biome bootstrap uses unbound holders, so inspect the key instead of value().
        return holder.unwrapKey()
                .map(key -> {
                    String path = key.location().getPath().toLowerCase(java.util.Locale.ROOT);
                    return path.startsWith("ore_") || path.endsWith("_ore") || path.contains("/ore_");
                })
                .orElse(false);
    }
}
