#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Sep 24 21:09:09 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
